name: Snyk Security Scan

on:
  push:
    branches:
      - main

jobs:
  snyk:
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        
      - name: Clean workspace
        run: sudo chown -R $USER:$USER .

      - name: Run Snyk Security Scan
        uses: snyk/actions/maven@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
